Story 22 (Function Expressions) tasks completed
Nadia982/development-practice pull request #12
Opened 2023-02-20 02:27 UTC by Nadia982

2023-02-20 07:33 UTC, gosimowicz requested changes

2023-02-20 07:33 UTC, gosimowicz commented on src/22_functionExpressions/task3.js
> +  innerFunction = () => "devMentor short function";
always use const (or let) - never define variables without any keyword (but variable innerFunction can be removed - it is related to AC 7. Note: all function implementations should be the shortest way, without {{{}}}

2023-02-22 00:22 UTC, Nadia982 commented on src/22_functionExpressions/task3.js
> +  innerFunction = () => "devMentor short function";
Hi Greg, I have made this update.

2023-02-24 06:44 UTC, gosimowicz approved these changes

2023-02-27 01:23 UTC, merged