Story 23 (Object) tasks completed
Nadia982/development-practice pull request #13
Opened 2023-02-21 02:15 UTC by Nadia982

2023-02-21 10:16 UTC, gosimowicz requested changes

2023-02-21 10:16 UTC, gosimowicz commented on src/23_object/task1.js
> +const printHuman = (obj) => {
rename obj to human - variable names should be self descriptive

2023-02-22 00:41 UTC, Nadia982 commented on src/23_object/task1.js
> +human.isDeveloper = false;
Updated - thanks

2023-02-22 00:42 UTC, Nadia982 commented on src/23_object/task1.js
> +  let values = Object.values(obj);
Updated - thanks

2023-02-22 00:42 UTC, Nadia982 commented on src/23_object/task1.js
> +const printHuman = (obj) => {
Updated - thanks

2023-02-24 06:47 UTC, gosimowicz approved these changes

2023-02-24 06:47 UTC, gosimowicz commented on src/23_object/task1.js
> +      `${human.firstName} ${human.lastName} (${human.age}) is not a developer`
your solution is ok (do not change it) but please remember that it can be done like this:
```
const printHuman = (human) => 
    `${human.firstName} ${human.lastName} (${human.age}) ${human.isDeveloper ? 'is' : 'is not'} a developer`
```

2023-02-24 06:47 UTC, gosimowicz commented on src/23_object/task1.js
> +  if (human.isDeveloper === true) {
if (human.isDeveloper) would be enough

2023-02-27 01:23 UTC, merged